#!/bin/bash
set -e
set -o pipefail
set -u

function check-disk-space {
    DISK_AVAILABLE_BEFORE_TRIM=${DISK_AVAILABLE_BEFORE_TRIM:-10485760} # 10GB

    disk_avail=$(df -k --output=avail "$AGENT_DIR" | tail -n1)
    echo "Disk space free: $(df -k -h --output=avail "$AGENT_DIR" | tail -n1 | sed -e 's/^[[:space:]]//')"

    if [[ $disk_avail -lt $DISK_AVAILABLE_BEFORE_TRIM ]]; then
        echo "Not enough disk space free, cutoff is ${DISK_AVAILABLE_BEFORE_TRIM} :floppy_disk:" >&2
        return 1
    fi

    return 0
}

AGENT_DIR="/var/lib/buildkite-agent/builds/"
# Scope this var to this buildkite agent, so that we do not interfere with the builds from any other agents on this machine.
BUILDS_DIR="$AGENT_DIR$BUILDKITE_AGENT_NAME/"

echo "~~~ :broom: Running trim-builds plugin"
echo "Checking disk space to see if old builds need to be trimmed"

echo "Checking disk space"
if ! check-disk-space ; then
    # If the build dir does not exist, this agent doesn't have old builds to trim - nothing to do here.
    if [ ! -d "$BUILDS_DIR" ]; then
        echo "Build directory not found: $BUILDS_DIR - there are no old builds for this agent to be purged."
        exit 0
    else 
        echo "Cleaning up past builds for this agent to make disk space"
        rm -rf "$BUILDS_DIR"
    fi

    echo "Checking disk space again"
    if ! check-disk-space ; then 
        echo "Disk health checks failed" >&2
        exit 1
    fi
fi

echo "Sufficient disk space available - proceeding!"
exit 0